version: '3'
services:
  kafka:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: kafka
    user: root
    image: yowko/kafkanozk:v1
    environment:
      - KAFKA_CREATE_TOPICS=yowkotest:3:1,yowkodemo:3:1
    ports:
      - "9092:9092"